<a href="https://colab.research.google.com/github/23f1002879/Pytorch-Computer-Vision/blob/master/notebooks/01_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd

In [2]:
# creating a tensor
x = torch.tensor([[1,2,3],[4,5,6]])
print(f'The tensor is {x}')
print('-'*50)
print('-'*50)
print(f'The shape of the tensor is {x.shape}')

The tensor is tensor([[1, 2, 3],
        [4, 5, 6]])
--------------------------------------------------
--------------------------------------------------
The shape of the tensor is torch.Size([2, 3])


In [3]:
# Some tensor Operation
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(f' The Adddition of the tensor is {a+b}')
print('-'*50)
print('-'*50)
print(f' The Subtraction of the tensor is {a-b}')

 The Adddition of the tensor is tensor([5, 7, 9])
--------------------------------------------------
--------------------------------------------------
 The Subtraction of the tensor is tensor([-3, -3, -3])


In [4]:
# Some Matrix Operation
# help(torch.rand) Learning about torch.rand() function

a = torch.rand(2,3)
b = torch.rand(3,2)

print('The matrix A is' , a)
print('_'*50)
print('_'*50)
print('The matrix B is' , b)
print('_'*50)
print('_'*50)
print(f'{torch.matmul(a,b)}')

The matrix A is tensor([[0.5991, 0.4476, 0.9753],
        [0.9903, 0.1861, 0.6741]])
__________________________________________________
__________________________________________________
The matrix B is tensor([[0.7540, 0.6213],
        [0.7992, 0.5558],
        [0.8033, 0.6784]])
__________________________________________________
__________________________________________________
tensor([[1.5930, 1.2827],
        [1.4369, 1.1760]])


In [5]:
# Tensor Shapes

x = torch.rand(2,3,4)
x.shape  # Two tensors will form of shape (3,4)
print('_'*50)
print(f'The initial shape of the tensor is {x.shape}')
print('_'*50)
print(x)

# Reshaping the tensor

x = x.reshape(6,4)
# x = x.reshape(2,12)
print('_'*50)
print(f'The new shape of the tensor is {x.shape}')
print('_'*50)
print(x)


# The total number of elements in a tensor must be same before and after applying the reshaping.

__________________________________________________
The initial shape of the tensor is torch.Size([2, 3, 4])
__________________________________________________
tensor([[[0.5144, 0.0893, 0.4441, 0.7228],
         [0.0077, 0.2526, 0.4928, 0.0047],
         [0.4100, 0.2966, 0.2887, 0.3564]],

        [[0.6150, 0.8338, 0.1484, 0.1785],
         [0.1416, 0.0724, 0.8706, 0.1833],
         [0.1742, 0.4420, 0.4581, 0.0948]]])
__________________________________________________
The new shape of the tensor is torch.Size([6, 4])
__________________________________________________
tensor([[0.5144, 0.0893, 0.4441, 0.7228],
        [0.0077, 0.2526, 0.4928, 0.0047],
        [0.4100, 0.2966, 0.2887, 0.3564],
        [0.6150, 0.8338, 0.1484, 0.1785],
        [0.1416, 0.0724, 0.8706, 0.1833],
        [0.1742, 0.4420, 0.4581, 0.0948]])


In [6]:
# Checking for GPU
device = 'cuda' if torch.cuda.is_available() else 'CPU'
print(device)

cuda


In [10]:
# The automatic differentiation
x = torch.tensor(3.0, requires_grad=True) # The require_grad method makes the computational graph i.e it will keep a track of every operation which we will perform on that tensor.
print(x)

y = x**3 + 2*x**2 + 10

y.backward() # .backward() function triggers the chain rule of the calculus
print(x.grad)

tensor(3., requires_grad=True)
tensor(39.)


In [13]:
# Setting up a simple linear regression model

import torch.nn as nn

model = nn.Linear(3,1)

x = torch.rand(1,3)
y = torch.rand(1,3)

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [14]:
for epoch in range(100):

    pred = model(x)

    loss = criterion(pred,y)

    optimizer.zero_grad() # This clears out (resets to zero) all the old gradients stored in the model from the previous loop.

    loss.backward()

    optimizer.step()

print(loss.item())

0.055744756013154984


/usr/local/lib/python3.12/dist-packages/torch/nn/modules/loss.py:626: UserWarning: Using a target size (torch.Size([1, 3])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
