<a href="https://colab.research.google.com/github/23f1002879/Pytorch-Computer-Vision/blob/master/notebooks/01_PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd

In [3]:
# creating a tensor
x = torch.tensor([[1,2,3],[4,5,6]])
print(f'The tensor is {x}')
print('-'*50)
print('-'*50)
print(f'The shape of the tensor is {x.shape}')

The tensor is tensor([[1, 2, 3],
        [4, 5, 6]])
--------------------------------------------------
--------------------------------------------------
The shape of the tensor is torch.Size([2, 3])


In [6]:
# Some tensor Operation
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

print(f' The Adddition of the tensor is {a+b}')
print('-'*50)
print('-'*50)
print(f' The Subtraction of the tensor is {a-b}')

 The Adddition of the tensor is tensor([5, 7, 9])
--------------------------------------------------
--------------------------------------------------
 The Subtraction of the tensor is tensor([-3, -3, -3])


In [13]:
# Some Matrix Operation
# help(torch.rand) Learning about torch.rand() function

a = torch.rand(2,3)
b = torch.rand(3,2)

print('The matrix A is' , a)
print('_'*50)
print('_'*50)
print('The matrix B is' , b)
print('_'*50)
print('_'*50)
print(f'{torch.matmul(a,b)}')

The matrix A is tensor([[0.8848, 0.5699, 0.2453],
        [0.4973, 0.1305, 0.1515]])
__________________________________________________
__________________________________________________
The matrix B is tensor([[0.5159, 0.7687],
        [0.4416, 0.6681],
        [0.6400, 0.7589]])
__________________________________________________
__________________________________________________
tensor([[0.8651, 1.2471],
        [0.4111, 0.5844]])


In [22]:
# Tensor Shapes

x = torch.rand(2,3,4)
x.shape  # Two tensors will form of shape (3,4)
print('_'*50)
print(f'The initial shape of the tensor is {x.shape}')
print('_'*50)
print(x)

# Reshaping the tensor

x = x.reshape(6,4)
# x = x.reshape(2,12)
print('_'*50)
print(f'The new shape of the tensor is {x.shape}')
print('_'*50)
print(x)


# The total number of elements in a tensor must be same before and after applying the reshaping.

__________________________________________________
The initial shape of the tensor is torch.Size([2, 3, 4])
__________________________________________________
tensor([[[0.5599, 0.1258, 0.8646, 0.5473],
         [0.6848, 0.0625, 0.4684, 0.0286],
         [0.8458, 0.9232, 0.6648, 0.7628]],

        [[0.0597, 0.6318, 0.3986, 0.6977],
         [0.6341, 0.6841, 0.8689, 0.9111],
         [0.2046, 0.4996, 0.6292, 0.3743]]])
__________________________________________________
The new shape of the tensor is torch.Size([6, 4])
__________________________________________________
tensor([[0.5599, 0.1258, 0.8646, 0.5473],
        [0.6848, 0.0625, 0.4684, 0.0286],
        [0.8458, 0.9232, 0.6648, 0.7628],
        [0.0597, 0.6318, 0.3986, 0.6977],
        [0.6341, 0.6841, 0.8689, 0.9111],
        [0.2046, 0.4996, 0.6292, 0.3743]])


In [24]:
# Checking for GPU
device = 'cuda' if torch.cuda.is_available() else 'CPU'
print(device)

CPU
